grobidHome: ../grobid-home

corsAllowedOrigins: "*"
corsAllowedMethods: "OPTIONS,GET,PUT,POST,DELETE,HEAD"
corsAllowedHeaders: "X-Requested-With,Content-Type,Accept,Origin"

chemspotUrl: http://falcon.nims.go.jp/chemspot
chemDataExtractorUrl: http://falcon.nims.go.jp/cde
#chemDataExtractorUrl: http://localhost:8076

grobidQuantitiesUrl: http://falcon.nims.go.jp/quantities

pythonVirtualEnv:
pythonRedirectOutput: true

server:
  type: custom
  idleTimeout: 120 seconds
  applicationConnectors:
    - type: http
      port: 8072
  adminConnectors:
    - type: http
      port: 8073
  registerDefaultExceptionMappers: false
  maxThreads: 10
  maxQueuedRequests: 512
  acceptQueueSize: 2024

logging:
  level: DEBUG

  # Logger-specific levels.
  loggers:
    org.grobid.core.data.normalization.QuantityNormalizer: "OFF"
    org.grobid.core.engines.QuantityParser: "OFF"
    org.grobid.core.engines.ValueParser: "OFF"
    org.grobid.core.utilities.WordsToNumber: "OFF"

  appenders:
    - type: console
      threshold: INFO
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: logs/grobid-superconductors.log
      archivedLogFilenamePattern: logs/grobid-superconductors-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 50MB

timeZone: UTC
