version: "2"
services:
  cde:
    image: lfoppiano/chemdataextractor-api:0.0.1
    restart: always
    ports:
      - 8076:8080

  superconductors:
    image: lfoppiano/grobid-superconductors:0.2.1-SNAPSHOT-light
    restart: always
    ports:
      - 8072:8072
      - 8073:8073
    links:
      - "cde:cde.local"
      - "linking_module:linking_module.local"

  linking_module:
    image: lfoppiano/linking-module:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8090:8080
