version: "2"
services:
  cde:
    image: lfoppiano/chemdataextractor-api:0.0.1
    restart: always
    ports:
      - 8076:8080

  superconductors:
    image: lfoppiano/grobid-superconductors:0.2.1.light.azure
    restart: always
    ports:
      - 8072:8080
      - 8073:8081
    links:
      - "cde:cde.local"
      - "linking_module:linking_module.local"
      - "falcon.nims.go.jp:falcon.local"

  linking_module:
    image: lfoppiano/linking-module:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8090:8080
