version: "3.9"
services:
  cde:
    image: lfoppiano/chemdataextractor-api:0.0.1
    restart: always
    ports:
      - 8076:8080
    networks:
      net1:
        aliases:
          - "cde.local"

  linking_module:
    image: lfoppiano/linking-module:0.2.0
    restart: always
    ports:
      - 8090:8080
    networks:
      net1:
        aliases:
          - "linking_module.local"
      #  
      #  glutton:
      #    image: ...
      #    restart: always
      #    ports:


  superconductors:
    image: lfoppiano/grobid-superconductors:0.3.0-SNAPSHOT
    restart: always
    volumes:
      - /Users/lfoppiano/development/projects/grobid/grobid-superconductors/resources/config/config-docker.yml:/opt/grobid/grobid-superconductors/config.yml:ro
    #      - /Users/lfoppiano/development/projects/grobid/grobid-superconductors/resources/config/grobid.yaml:/opt/grobid/grobid-home/config/grobid.yaml:ro
    ports:
      - 8072:8072
      - 8073:8073
    networks:
      - net1
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [ gpu ]

networks:
  net1: