version: "2"
services:
  cde:
    image: lfoppiano/chemdataextractor-api:0.0.1
    restart: always
    ports:
      - 8076:8080

  linking_module:
    image: lfoppiano/linking-module:0.2.0
    restart: always
    ports:
      - 8090:8080
      
  superconductors:
    image: lfoppiano/grobid-superconductors:0.3.0-SNAPSHOT
    restart: always
    volumes:
#      - /Users/lfoppiano/development/projects/grobid/grobid-superconductors/resources/config/config.yml:/opt/grobid/grobid-superconductors/config.yml
      - /Users/lfoppiano/development/projects/grobid/grobid-home/config/grobid.yaml:/opt/grobid/grobid-home/config/grobid.yaml
    ports:
      - 8072:8072
      - 8073:8073
    links:
      - "cde:cde.local"
      - "linking_module:linking_module.local"
      - "falcon.nims.go.jp:falcon.local"
