name: Build release

on:
  push:
    branches: 
      - main
      - master
      - fix-release-docker
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    
concurrency:
  group: docker
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Test with Gradle Jacoco and Coveralls
        run: ./gradlew test jacocoTestReport coveralls --no-daemon
  
  docker-build:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Set tags
        id: set_tags
        run: |
          DOCKER_IMAGE=lfoppiano/grobid-superconductors
          VERSION=""
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="${VERSION}"
          else
            TAGS="latest"
          fi
          echo "TAGS=${TAGS}"
          echo ::set-output name=tags::${TAGS}
      - uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: lfoppiano/grobid-superconductors
          registry: docker.io
          pushImage: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.set_tags.outputs.tags }}
#          buildArgs: "GROBID_VERSION=${VERSION}"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
