name: Build unstable

on: [push]

concurrency: 
  group: gradle
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Test with Gradle Jacoco and Coveralls
      run: ./gradlew test jacocoTestReport coveralls --no-daemon

#    - name: Coveralls GitHub Action
#      uses: coverallsapp/github-action@v1.0.1
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    needs: [build]

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: set up proxy http
        run: echo -e "systemProp.http.proxyHost=wwwout.nims.go.jp\nsystemProp.http.proxyPort=8888\nsystemProp.http.nonProxyHosts=*.nims.go.jp,localhost\n\nsystemProp.https.proxyHost=wwwout.nims.go.jp\nsystemProp.https.proxyPort=8888\nsystemProp.https.nonProxyHosts=*.nims.go.jp,localhost" >> gradle.properties
      - name: check result proxy
        run: cat gradle.properties
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lfoppiano/grobid-superconductors:latest
      - name: Cleanup older than 24h images and containers
        run: docker cleanup --filter "until=24h" --force
