name: Run integration tests manually

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout grobid home
      uses: actions/checkout@v4
      with:
        repository: kermitt2/grobid
        path: ./grobid
    - name: Checkout grobid-superconductors
      uses: actions/checkout@v4
      with:
        path: ./grobid/grobid-superconductors
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10+7'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build and run integration tests
      working-directory: ./grobid/grobid-superconductors
      run: ./gradlew copyModels integration --no-daemon
   
