name: Docker Image CI falcon

# Only trigger, when the build workflow succeeded
on: 
  workflow_run:
    workflows: ["Java CI"]
    types:
      - completed
    
concurrency:
  group: docker
  cancel-in-progress: true

jobs:
  build:

#    runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: set up proxy http 
      run: echo "systemProp.http.proxyHost=wwwout.nims.go.jp\nsystemProp.http.proxyPort=8888\nsystemProp.http.nonProxyHosts=*.nims.go.jp,localhost\n\nsystemProp.https.proxyHost=wwwout.nims.go.jp\nsystemProp.https.proxyPort=8888\nsystemProp.https.nonProxyHosts=*.nims.go.jp,localhost" >> gradle.properties
    - name: check result proxy
      run: cat gradle.properties
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lfoppiano/grobid-superconductors:latest
