name: Docker Image CI falcon

on: [push, pull_request, workflow_dispatch]
#  workflow_run:
#    workflows: [ "Java CI" ]
#    types:
#      - completed

concurrency:
  group: docker
  cancel-in-progress: true

jobs:
  build:

    #    runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Set tags
        id: set_tags
        run: |
          DOCKER_IMAGE=lfoppiano/grobid-superconductors
          VERSION=""
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
          else
            TAGS="${DOCKER_IMAGE}_unstable:${GITHUB_SHA},${DOCKER_IMAGE}_unstable:latest"
          fi
          echo "TAGS=${TAGS}"
          echo ::set-output name=tags::${TAGS}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: set up proxy http
        run: echo -e "systemProp.http.proxyHost=wwwout.nims.go.jp\nsystemProp.http.proxyPort=8888\nsystemProp.http.nonProxyHosts=*.nims.go.jp,localhost\n\nsystemProp.https.proxyHost=wwwout.nims.go.jp\nsystemProp.https.proxyPort=8888\nsystemProp.https.nonProxyHosts=*.nims.go.jp,localhost" >> gradle.properties
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          tags: ${{ steps.set_tags.outputs.tags }}
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag ${TAGS}
