name: Docker Image CI falcon

# Only trigger, when the build workflow succeeded
on: 
  workflow_run:
    workflows: ["Java CI"]
    types:
      - completed
    
concurrency:
  group: docker
  cancel-in-progress: true

jobs:

  build:

#    runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lfoppiano/grobid-superconductors:latest
